import setLanguage from 'next-translate/setLanguage';
import useTranslation from 'next-translate/useTranslation';
import { Inter } from 'next/font/google';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export default () => {
  const { t, lang } = useTranslation('common');

  const oppositeLocale = lang === 'ru' ? 'en' : 'ru';

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={inter.style}>
        <h1 className="text-lg">{t('hello')}</h1>
        <button
          className="bg-brand-600 text-white px-4 py-3 rounded-md"
          onClick={() => setLanguage(oppositeLocale)}
        >
          Set lang
        </button>
      </main>
    </>
  );
};
